mysql:
    image: "mysql:8"
    container_name: "mysql"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: "rmtuser"
      MYSQL_DATABASE: "rmt"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
